import './globals.css'
import { Inter } from 'next/font/google'
import Link from "next/link";
const inter = Inter({ subsets: ['latin'] })
import { FaGithub, FaLinkedin, FaTwitter } from 'react-icons/fa';
import Loading from '@/components/Loading';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className + " bg-gradient-to-b from-bg-gradient-from to-bg-gradient-to min-h-screen text-white"}>
        <main className="p-4 max-w-2xl mx-auto">
          <header className="flex justify-between my-2 sm:my-8">
            <Link href="/" className="flex gap-1">
              <svg id="logo-16" width="109" height="43" viewBox="0 0 109 43" fill="none" xmlns="http://www.w3.org/2000/svg"> <path d="M64.9315 11.4284C62.1883 8.6852 58.9316 6.5091 55.3475 5.0245C51.7633 3.5399 47.9219 2.7758 44.0424 2.7758C40.1629 2.7758 36.3215 3.5399 32.7373 5.0245C29.1532 6.5091 25.8965 8.6852 23.1533 11.4284L44.0424 32.3174L64.9315 11.4284Z" class="ccompli1" fill="#FFD200"></path> <path d="M44.0686 32.3475C46.8118 35.0907 50.0684 37.2667 53.6526 38.7513C57.2367 40.2359 61.0782 41 64.9577 41C68.837 41 72.679 40.2359 76.263 38.7513C79.847 37.2667 83.104 35.0907 85.847 32.3475L64.9577 11.4584L44.0686 32.3475Z" class="ccompli2" fill="#06E07F"></path> <path d="M44.017 32.3429C41.2738 35.0861 38.0171 37.2621 34.433 38.7467C30.8488 40.2313 27.0074 40.9954 23.1279 40.9954C19.2484 40.9954 15.407 40.2313 11.8228 38.7467C8.2387 37.2621 4.982 35.0861 2.2388 32.3429L23.1279 11.4538L44.017 32.3429Z" class="ccustom" fill="#E3073C"></path> <path d="M64.9831 11.433C67.726 8.6898 70.983 6.5138 74.567 5.0292C78.151 3.5446 81.993 2.7805 85.872 2.7805C89.752 2.7805 93.593 3.5446 97.177 5.0292C100.761 6.5138 104.018 8.6898 106.761 11.433L85.872 32.3221L64.9831 11.433Z" class="ccustom" fill="#1F84EF"></path> </svg>

            </Link>
            <nav className="flex items-center gap-2 sm:gap-6 text-white/80 text-sm sm:text-bas">
              <Link href="/"><h1 className='text-lg md:text-xl hover:text-green-500 font-medium'>Home</h1></Link>
              <Link href="/pricing"><h1 className='text-lg md:text-xl hover:text-green-500 font-medium'>Pricing</h1></Link>
              <Link href="/contact"><h1 className='text-lg md:text-xl hover:text-green-500 font-medium'>Contact</h1></Link>
            </nav>
          </header>
          {children}
          <footer className="text-white py-4 text-center mt-4 md:mt-12">
            <h1 className='text-xl'>Empower Your Content with Captions</h1>
            <p className='text-sm text-zinc-500 leading-5 '>
            A caption generator is a powerful tool designed to enhance your multimedia content by adding text-based captions automatically. Whether you&apos;re sharing videos, images, or social media posts, captions play a crucial role in improving accessibility and engagement. By converting spoken content into readable text, caption generators ensure that your message reaches a wider audience, including individuals with hearing impairments and those in noisy environments. They offer customization options such as font styles, colors, and formatting to align with your brand&apos;s identity. Moreover, caption generators contribute to search engine optimization (SEO) by making your content more discoverable and enhancing viewer retention on various platforms. Embrace the efficiency and inclusivity of captioning today to elevate your content&apos;s impact and accessibility effortlessly.
            </p>
            <div className='flex gap-6 justify-center mt-8 text-3xl '>
              <FaGithub className='hover:text-green-500 cursor-pointer'/>
              <FaLinkedin className='hover:text-blue-500 cursor-pointer'/>
              <FaTwitter className='hover:text-red-500 cursor-pointer' />
            </div>
            
          </footer>
        </main>

      </body>
    </html>
  )
}